version: '3.8'

services:
  shop.api:
    container_name: shop.api
    image: shop.api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
      - ASPNETCORE_HTTPS_PORTS=3001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/shop.pfx
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - database.server

  database.server:
    image: postgres:latest
    container_name: postgres.db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shop.client:
    build:
      context: ClientApp/
      dockerfile: Dockerfile
    image: shop.client
    container_name: shop.client
    ports:
      - "5000:5000"
    depends_on:
      - shop.api

volumes:
  postgres_data:
